config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'requests#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :requests, only: [:show, :new, :create, :destroy] do
    resources :matches, only: [:index, :create]
  end
  resources :matches, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :request
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :matchs, dependent: :destroy

  validates :date, :time, :location, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:location, :date],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
  has_many :matchs, dependent: :destroy
  has_one_attached :photo

  validates :first_name, :level, :address, :gender, presence: true
  LEVEL = ["NC", "40", "30/5", "30/4", "30/3", "30/2", "30/1", "30", "15/5", "15/4", "15/3", "15/2", "15/1", "15", "5/6", "4/6", "3/6", "2/6", "1/6", "0", "-2/6", "-4/6", "-15", "-30"]
  GENDER = ["Man", "Woman"]
  validates :level, inclusion: { in: LEVEL }
  validates :gender, inclusion: { in: GENDER }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :level, :address, :gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :level, :address, :gender, :photo])
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.where(user_id: current_user)
  end

  def create
    @match = Match.new
    request = Request.find(params["request_id"])
    @match.user = current_user
    @match.request = request
    if @match.save
      redirect_to request_matches_path(@match)
    else
      redirect_to request_path(@match.request)
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to request_matches_path(@match.request)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @requests = Request.global_search(params[:query])
    else
      @requests = Request.all
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    @request = Request.new
    @requests = Request.where(user_id: current_user)
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    if @request.save
      redirect_to new_request_path(@request)
    else
      render :new
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to new_request_path
  end

  private

  def request_params
    params.require(:request).permit(:date, :time, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tennismatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/matches/index.html.erb
<div class="margin-top min-100-vh">
  <% if !@matches.empty? %>
    <h1 class="h1-match">Your next matches are</h1>
    <div class="card-container ml-5">
      <% @matches.each do |match| %>
        <div class="card">
          <%= cl_image_tag "#{match.request.user.photo.key}", class: "card-avatar" %>
            <h3><%= "#{match.request.user.first_name} - #{match.request.location}" %></h3>
            <p><%= match.request.date.strftime("%d %B") %></p>
            <p><%= match.request.time.strftime("%I:%M %p") %></p>
            <%= link_to match_path(match), method: :delete, data: {confirm:("Do you want to remove this match?")} do %>
              <i id="trash" class="fas fa-trash-alt fa-fw"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <h1 class="h1-match">No match to come</h1>
  <% end %>
</div>

app/views/requests/index.html.erb
<div class="banner min-100-vh" style="background-image: url('<%= image_path "Tenniscourt.jpg" %>')">
  <div class="banner-text">
    <div>
      <p>Choose your next game!</p>
      <div class = 'form-group'>
        <%= form_tag root_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mt-3",
          placeholder: "Where would you like to play?"
        %>
        <%= submit_tag "Search", class: "btn mt-3" %>
        <% end %>
      </div>

    </div>

    <div class="raquette">
      <img id="raquette" src="<%= asset_path('raquette1.png')%>" alt="raquette">
    </div>
  <div class="ball-container">
    <div class="ball"></div>
    <div class="shadow"></div>
  </div>
  </div>
</div>

<h2>They are looking for a partner ...</h2>

<div class="card-container">
  <% @requests.each do |request| %>
    <% if request.matchs.empty? %>
      <%= link_to request_path(request) do %>
        <div class="card">
          <% if request.user.photo.attached? %>
            <%= cl_image_tag "#{request.user.photo.key}", crop: :fill, class: "card-avatar" %>
          <% else %>
             <%= image_tag request.user.gender == "Man" ? "avatar_man.svg" : "avatar_woman.svg", crop: :fill, class: "card-avatar bg-white" %>
          <% end %>
          <h3><%= request.user.first_name %></h3>
          <p>
            <i class="fas fa-map-marked-alt"></i>
            <strong><%= request.location %> </strong>
          </p>
          <p>
            <i class="far fa-calendar-alt"></i>
            <%= request.date.strftime("%d %B") %>
          </p>
          <p>
            <i class="far fa-clock text-center"></i>
            <%= request.time.strftime("%I:%M %p") %>
          </p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/requests/new.html.erb
<div class="matches">
  <div class="form">
    <h3>Propose a new match</h3>
    <%= form_for (@request) do |f| %>
     <%= f.label :date, class: "mt-3" %>
    <%= f.date_field :date, class: "form-control" %>
    <%= f.label :time, class: "mt-3"  %>
    <%= f.time_field :time, class: "form-control" %>
     <%= f.label :location, class: "mt-3" %>
    <%= f.text_field :location, class: "form-control" %>
    <%= f.submit class: "card-btn" %>
  <% end %>
  </div>
  <div class="form-match">
    <div class="">
      <h3> My next matches </h3>
      <ul>
        <% @requests.each do |request| %>
            <p>
              <%= request.date.strftime("%d %B") %> - <%= request.time.strftime("%I:%M %p") %>  <%= request.location %>
              <%= link_to request_path(request), method: :delete, data: {confirm: "Do you really want to delete it?"} do %>
                <i class="fas fa-trash-alt fa-fw"></i>
              <% end %>
            </p>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
  <div class="profile">
    <div class="profile-container">
      <%= cl_image_tag "#{@request.user.photo.key}", class: "avatar" %>
      <h3><%= @request.user.first_name %></h3>
      <p><%= @request.user.birth_date %></p>
      <p><%= @request.user.address %>
      <% if @request.user.address.upcase == "SUISSE" %>
      <img src="https://img.icons8.com/color/48/000000/switzerland.png"/>
      <% else %>
      <% end %>
      <% if @request.user.address.upcase == "SERBIE" %>
      <img src="https://img.icons8.com/color/48/000000/serbia.png"/>
      <% else %>
      <% end %>
      <% if @request.user.address.upcase == "AUTRICHE" %>
      <img src="https://img.icons8.com/color/48/000000/austria.png"/>
      <% else %>
      <% end %>
      <% if @request.user.address.upcase == "GRECE" %>
      <img src="https://img.icons8.com/color/48/000000/greece.png"/>
      <% else %>
      <% end %>
      <% if @request.user.address.upcase == "ESPAGNE" %>
      <img src="https://img.icons8.com/color/48/000000/spain.png"/>
      <% else %>
      <% end %>
      </p>
      <p><%= @request.user.description %></p>
      <p><%= @request.user.level %></p>
    </div>
    <div class="requests">
      <ul class="requests-list">
        <% Request.where(user_id: @request.user_id).each do |request|%>
          <% if request.matchs.empty? %>
            <%= link_to request_matches_path(request), method: :post, data: {confirm: "Do you want to check this match?" } do %>
              <li class="list">
                <p><%= request.date.strftime("%d %B") %></p>
                <p><%= request.time.strftime("%I:%M %p") %></p>
                <p><%= request.location %></p>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    <div class="balles">
      <img id="balles" src="<%= asset_path('balles.png')%>" alt="balles">
    </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links list-inline">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1><strong>Tennis</strong>match <img src="https://img.icons8.com/pastel-glyph/64/000000/tennis-ball--v2.png"/></h1>

  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="card-btn btn-nav mt-0 mb-0 ml-0 mr-3">
          <%= link_to "Challenge someone", new_request_path %>
        </div>
      </li>
      <% if user_signed_in? == false %>
      <li class="nav-item active">
        <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>

      <% if current_user %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag "#{current_user.photo.key}", width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
             <%= image_tag current_user.gender == "Man" ? "avatar_man.svg" : "avatar_woman.svg", width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", request_matches_path(:request_id), class: "dropdown-item" %>
            <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>

    </ul>
  </div>
</div>